L1:  EQU 1
L2:  EQU 0
L:   EQU 4
L3:  CONST -4
TESTE: MACRO
ADD DOIS
STORE SPACE
ENDMACRO
SECTION TEXT
IF L1
LOAD SPACE ;faz esta opera ̧c~ao se L1 for verdadeiro
IF L2
INPUT SPACE ;faz esta opera ̧c~ao se L2 for verdadeiro
TESTE
SECTION DATA
N: SPACE
DOIS: CONST 2

